version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    container_name: mysql-container
    restart: always
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789

  api:
    build: "./backend"
    restart: always
    container_name: spring-api-container
    ports:
      - 8080:8080
    depends_on:
      - db