version: '3.8'

services:

  db:
    image: mysql
    command: --init-file /data/application/init.sql --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
      - 33060:33060
    restart: always
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
  # api:
  #   build: "./backend"
  #   restart: always
  #   container_name: api
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
#     networks:
#       - market-app
# networks:
#   market-app: